### PR TITLE
Small updates

### LINKED ISSUE #155: Open Gallery deletes previously set pictures in forms if there is no submission
## Expected behavior
A clear and concise description of what should happen.
The open gallery function should leave previously set pictures if a submission is canceled

## Actual behavior
A description of what is currently happening. (What's the bug?)
Previously set pictures are getting deleted upon cancel, leaving the field empty 

## Steps to reproduce
Steps to reproduce the bug:
1. Go to '...' Election Application
2. Click on '...' Avatar and set picture, then press cancel
3. See error

## Additional context
Add any other context about the problem here, such as the device the problem occurs in.
// onPress = { () => {
					// 	openGallery(
					// 		`/election/positions/${candidate.position || positionSelected}/candidates/${this.props.id}`,
					// 		this.props.id,
					// 		(url) => {
					// 			let candidate = Object.assign({}, this.state.candidate);
					// 			candidate.picture = url;

					// 			this.setState({ candidate });
					// 		}
					// 	);
					// } }

### PR DESCRIPTION
**Pull request by esteban737**
Fixes #155

## Description
 Fixed flickering issues on some screens and reincorporated candidate picture selection into the application screen. Fixed other UI issues on other screens.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (specify below)
Styling

## Checklist:

- [x] My code follows the code style of this project found on [Contribution guidelines](https://github.com/SHPEUCF/shpeucfapp/wiki/Contribution-guidelines).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/screens/Election/ElectionBallot.js [hunk 1]
```diff
@@ -303,16 +317,29 @@ const styles = {
...
 		padding: "6%"
 	},
 	modalBackground: {
 		alignItems: "center",
 		height: "100%",
-		justifyContent: "center"
+		justifyContent: "center",
+		backgroundColor: "#000a"
+	},
+	closeModalBar: { backgroundColor: "#FECB00",
```
Comment (idelmr) [inline src/screens/Election/ElectionBallot.js:330]: Place bgcolor in a new line.
