### PR TITLE
fixed issue where colleges weren't loaded correctly

### LINKED ISSUE #145: Colleges weren't being loaded in correctly in registration
## Expected behavior
Colleges weren't being loaded in correctly in registration

## Actual behavior
You can't pick colleges in registration Picker Input because they aren't being loaded in correctl

### PR DESCRIPTION
**Pull request by HanielDiaz**
Fixes #145 

## Description
Loads colleges json correctly

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (specify below)

## Checklist:

- [x] My code follows the code style of this project found on [Contribution guidelines](https://github.com/SHPEUCF/shpeucfapp/wiki/Contribution-guidelines).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/components/auth/RegistrationForm.js [hunk 1]
```diff
@@ -115,12 +115,14 @@ class RegistrationForm extends Component {
...
 		} = this.props;
 
-		const p1 = college && college !== "" && college != "Do not wish to disclose"
+		const p1 = colleges && college !== ""
 			? <PickerInput
 				title = { "Major" }
+				value = { major }
 				data = { colleges[college] }
 				placeholder = { "Select major" }
 				onSelect = { (text) => majorChanged(text) }
```
Comment (idelmr) [inline src/components/auth/RegistrationForm.js:128]: Change the `View` 2 lines to be self-closing.

File: src/components/auth/RegistrationForm.js [hunk 2]
```diff
@@ -115,12 +115,14 @@ class RegistrationForm extends Component {
 		const {
 			college,
 			collegeChanged,
+			major,
 			majorChanged
 		} = this.props;
 
-		const p1 = college && college !== "" && college != "Do not wish to disclose"
+		const p1 = colleges && college !== ""
```
Comment (idelmr) [inline src/components/auth/RegistrationForm.js:122]: Since "" is false, this can be changed to `colleges && college`, unless explicitly needed or ends up being confusing.

File: src/components/auth/RegistrationForm.js [hunk 3]
```diff
@@ -131,10 +133,12 @@ class RegistrationForm extends Component {
 			<View>
 				<PickerInput
 					title = { "Colleges" }
+					value = { college }
 					data = { colleges }
 					placeholder = { "Select college" }
 					onSelect = { (text) => collegeChanged(text) } />
 				{ p1 }
+
```
Comment (idelmr) [inline src/components/auth/RegistrationForm.js:141]: Remove empty line.
